import json
import os

import requests

MODEL = "claude-sonnet-5"
API_URL = "https://api.anthropic.com/v1/messages"

SYSTEM = (
    "You are a senior application-security analyst writing the narrative of an automated "
    "pentest report. You are given a JSON array of findings that security tools (OWASP ZAP, "
    "Nuclei, sqlmap) and custom checks produced against a target. Each finding has a stable "
    "integer 'index'. Your job is ONLY to explain and prioritize what the tools found.\n"
    "STRICT RULES:\n"
    "1. Write only about findings present in the provided JSON. Never invent or imply a "
    "vulnerability that is not in the list.\n"
    "2. NEVER change the tool-assigned severity of any finding. You may write a one-line "
    "justification of WHY a finding carries its severity, but the tool's value is final.\n"
    "3. Remediation must be a suggested METHOD or approach, in prose — describe WHAT to do, "
    "not HOW to write it. NEVER output a code snippet. One or two sentences.\n"
    "4. The tools did the detection; you are the analyst/writer. Do not phrase anything as if "
    "you personally discovered the issues.\n"
    "5. The non-technical summary is for a reader with NO security background (a manager or "
    "client). Plain language, short sentences, active voice, no jargon; if a term is "
    "unavoidable, define it in a few words. Translate each significant finding into a real-world "
    "consequence. Neutral and factual, not alarmist.\n"
    "Return ONLY a JSON object, no prose around it, with this exact shape:\n"
    '{"summary": "<2-4 sentence executive summary>", '
    '"non_technical_summary": "<plain-language summary for a non-technical reader>", '
    '"per_finding": {"<index>": {"justification": "<one line on why this severity>", '
    '"remediation": "<suggested method, 1-2 sentences, never code>"}}}'
)

def generate_narrative(findings: list[dict], target: str, coverage_notes: str = "",
                       api_key: str | None = None, workspace_id: str | None = None) -> dict | None:
    api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")
    workspace_id = workspace_id or os.environ.get("ANTHROPIC_WORKSPACE_ID")
    if not api_key or not findings:
        return None

    payload_findings = [
        {"index": i, **{k: f.get(k) for k in ("category", "tool", "severity", "endpoint", "description")}}
        for i, f in enumerate(findings)
    ]
    user = (
        f"Target: {target}\nCoverage: {coverage_notes or 'n/a'}\n"
        f"Findings JSON (each has a stable 'index'):\n{json.dumps(payload_findings, indent=2)}"
    )
    headers = {"x-api-key": api_key, "anthropic-version": "2023-06-01", "content-type": "application/json"}
    if workspace_id:
        headers["anthropic-workspace-id"] = workspace_id
    body = {"model": MODEL, "max_tokens": 3000, "system": SYSTEM,
            "messages": [{"role": "user", "content": user}]}
    try:
        r = requests.post(API_URL, headers=headers, json=body, timeout=120)
        if r.status_code != 200:
            print(f"[writer] Claude API {r.status_code}: {r.text[:200]} — falling back to template")
            return None
        text = "".join(b.get("text", "") for b in r.json().get("content", []) if b.get("type") == "text").strip()
        if text.startswith("```"):
            text = text.split("```", 2)[1].lstrip("json").strip() if "```" in text else text
        data = json.loads(text)
        if isinstance(data, dict) and "summary" in data:
            data.setdefault("per_finding", {})
            data.setdefault("non_technical_summary", "")
            data["per_finding"] = {str(k): v for k, v in (data.get("per_finding") or {}).items()}
            print("[writer] narrative generated by claude-sonnet-5")
            return data
    except Exception as e:
        print(f"[writer] error {type(e).__name__}: {e} — falling back to template")
    return None
